import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      
      <body className="bg-[black] text-white">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
